#!/usr/bin/with-contenv bash

# copy

mkdir -p /config/qBittorrent/config/
[[ ! -f /config/qBittorrent/config/qBittorrent.conf ]] && cp /defaults/qBittorrent.conf /config/qBittorrent/config/qBittorrent.conf

#检查Search文件，并创建.
if [ ! -d "/config/qBittorrent/data/nova3/engines" ] ;  then 
mkdir -p /config/qBittorrent/data/nova3/engines
fi
cp -ru /defaults/Search/*  /config/qBittorrent/data/nova3/engines

# permissions
if [ "$FIX" == "YES" ];then
chown abc:abc -R \
	/mnt \
	/config
fi