#!/usr/bin/with-contenv bash

# copy

[[ ! -f /config/qBittorrent/config/qBittorrent.conf ]] && cp /defaults/qBittorrent.conf /config/qBittorrent/config/qBittorrent.conf

# permissions
if [ "$FIX" == "YES" ];then
chown abc:abc -R \
	/mnt \
	/config
fi