#!/usr/bin/with-contenv bash

# copy

[[ ! -f /config/qBittorrent/config/qBittorrent.conf ]] && cp /defaults/qBittorrent.conf /config/qBittorrent/config/qBittorrent.conf

# permissions

chown abc:abc -R \
	/mnt \
	/config